spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java?useSSL=false
    username: root
    password: 123456

  jackson:
    serialization:
      write-dates-as-timestamps: true

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    com.template: debug

file:
  mode: local
  local:
    cache: C:\Users\Hery\Desktop\cache
    save: C:\Users\Hery\Desktop\upload

