spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址（默认be）
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

  jackson:
    serialization:
      write-dates-as-timestamps: true

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    com.template: debug

file:
  mode: local
  local:
    cache: C:\Users\Hery\Desktop\cache
    save: C:\Users\Hery\Desktop\upload

